/*
	Note: This file is autogenerated! Do not edit it manually!
	Edit client_company_template.go instead, and run
	hack/generate-client.sh afterwards.
*/

package client

import (
	"fmt"

	api "github.com/cloud-native-nordics/meetup-kit/pkg/apis/meetops"

	log "github.com/sirupsen/logrus"
	"github.com/weaveworks/gitops-toolkit/pkg/runtime"
	"github.com/weaveworks/gitops-toolkit/pkg/storage"
	"github.com/weaveworks/gitops-toolkit/pkg/storage/filterer"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// CompanyClient is an interface for accessing Company-specific API objects
type CompanyClient interface {
	// New returns a new Company
	New() *api.Company
	// Get returns the Company matching given UID from the storage
	Get(runtime.UID) (*api.Company, error)
	// Set saves the given Company into persistent storage
	Set(*api.Company) error
	// Patch performs a strategic merge patch on the object with
	// the given UID, using the byte-encoded patch given
	Patch(runtime.UID, []byte) error
	// Find returns the Company matching the given filter, filters can
	// match e.g. the Object's Name, UID or a specific property
	Find(filter filterer.BaseFilter) (*api.Company, error)
	// FindAll returns multiple Companys matching the given filter, filters can
	// match e.g. the Object's Name, UID or a specific property
	FindAll(filter filterer.BaseFilter) ([]*api.Company, error)
	// Delete deletes the Company with the given UID from the storage
	Delete(uid runtime.UID) error
	// List returns a list of all Companys available
	List() ([]*api.Company, error)
}

// Companys returns the CompanyClient for the IgniteInternalClient instance
func (c *MeetOpsInternalClient) Companys() CompanyClient {
	if c.companyClient == nil {
		c.companyClient = newCompanyClient(c.storage, c.gv)
	}

	return c.companyClient
}

// companyClient is a struct implementing the CompanyClient interface
// It uses a shared storage instance passed from the Client together with its own Filterer
type companyClient struct {
	storage  storage.Storage
	filterer *filterer.Filterer
	gvk      schema.GroupVersionKind
}

// newCompanyClient builds the companyClient struct using the storage implementation and a new Filterer
func newCompanyClient(s storage.Storage, gv schema.GroupVersion) CompanyClient {
	return &companyClient{
		storage:  s,
		filterer: filterer.NewFilterer(s),
		gvk:      gv.WithKind(api.KindCompany.Title()),
	}
}

// New returns a new Object of its kind
func (c *companyClient) New() *api.Company {
	log.Tracef("Client.New; GVK: %v", c.gvk)
	obj, err := c.storage.New(c.gvk)
	if err != nil {
		panic(fmt.Sprintf("Client.New must not return an error: %v", err))
	}
	return obj.(*api.Company)
}

// Find returns a single Company based on the given Filter
func (c *companyClient) Find(filter filterer.BaseFilter) (*api.Company, error) {
	log.Tracef("Client.Find; GVK: %v", c.gvk)
	object, err := c.filterer.Find(c.gvk, filter)
	if err != nil {
		return nil, err
	}

	return object.(*api.Company), nil
}

// FindAll returns multiple Companys based on the given Filter
func (c *companyClient) FindAll(filter filterer.BaseFilter) ([]*api.Company, error) {
	log.Tracef("Client.FindAll; GVK: %v", c.gvk)
	matches, err := c.filterer.FindAll(c.gvk, filter)
	if err != nil {
		return nil, err
	}

	results := make([]*api.Company, 0, len(matches))
	for _, item := range matches {
		results = append(results, item.(*api.Company))
	}

	return results, nil
}

// Get returns the Company matching given UID from the storage
func (c *companyClient) Get(uid runtime.UID) (*api.Company, error) {
	log.Tracef("Client.Get; UID: %q, GVK: %v", uid, c.gvk)
	object, err := c.storage.Get(c.gvk, uid)
	if err != nil {
		return nil, err
	}

	return object.(*api.Company), nil
}

// Set saves the given Company into the persistent storage
func (c *companyClient) Set(company *api.Company) error {
	log.Tracef("Client.Set; UID: %q, GVK: %v", company.GetUID(), c.gvk)
	return c.storage.Set(c.gvk, company)
}

// Patch performs a strategic merge patch on the object with
// the given UID, using the byte-encoded patch given
func (c *companyClient) Patch(uid runtime.UID, patch []byte) error {
	return c.storage.Patch(c.gvk, uid, patch)
}

// Delete deletes the Company from the storage
func (c *companyClient) Delete(uid runtime.UID) error {
	log.Tracef("Client.Delete; UID: %q, GVK: %v", uid, c.gvk)
	return c.storage.Delete(c.gvk, uid)
}

// List returns a list of all Companys available
func (c *companyClient) List() ([]*api.Company, error) {
	log.Tracef("Client.List; GVK: %v", c.gvk)
	list, err := c.storage.List(c.gvk)
	if err != nil {
		return nil, err
	}

	results := make([]*api.Company, 0, len(list))
	for _, item := range list {
		results = append(results, item.(*api.Company))
	}

	return results, nil
}
