// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	meetops "github.com/cloud-native-nordics/meetup-kit/pkg/apis/meetops"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Company)(nil), (*meetops.Company)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Company_To_meetops_Company(a.(*Company), b.(*meetops.Company), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.Company)(nil), (*Company)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_Company_To_v1alpha1_Company(a.(*meetops.Company), b.(*Company), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CompanyRef)(nil), (*meetops.CompanyRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CompanyRef_To_meetops_CompanyRef(a.(*CompanyRef), b.(*meetops.CompanyRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.CompanyRef)(nil), (*CompanyRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_CompanyRef_To_v1alpha1_CompanyRef(a.(*meetops.CompanyRef), b.(*CompanyRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Meetup)(nil), (*meetops.Meetup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Meetup_To_meetops_Meetup(a.(*Meetup), b.(*meetops.Meetup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.Meetup)(nil), (*Meetup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_Meetup_To_v1alpha1_Meetup(a.(*meetops.Meetup), b.(*Meetup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MeetupGroup)(nil), (*meetops.MeetupGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MeetupGroup_To_meetops_MeetupGroup(a.(*MeetupGroup), b.(*meetops.MeetupGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.MeetupGroup)(nil), (*MeetupGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_MeetupGroup_To_v1alpha1_MeetupGroup(a.(*meetops.MeetupGroup), b.(*MeetupGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MeetupGroupSpec)(nil), (*meetops.MeetupGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MeetupGroupSpec_To_meetops_MeetupGroupSpec(a.(*MeetupGroupSpec), b.(*meetops.MeetupGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.MeetupGroupSpec)(nil), (*MeetupGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_MeetupGroupSpec_To_v1alpha1_MeetupGroupSpec(a.(*meetops.MeetupGroupSpec), b.(*MeetupGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MeetupGroupStatus)(nil), (*meetops.MeetupGroupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MeetupGroupStatus_To_meetops_MeetupGroupStatus(a.(*MeetupGroupStatus), b.(*meetops.MeetupGroupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.MeetupGroupStatus)(nil), (*MeetupGroupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_MeetupGroupStatus_To_v1alpha1_MeetupGroupStatus(a.(*meetops.MeetupGroupStatus), b.(*MeetupGroupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MeetupSpec)(nil), (*meetops.MeetupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MeetupSpec_To_meetops_MeetupSpec(a.(*MeetupSpec), b.(*meetops.MeetupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.MeetupSpec)(nil), (*MeetupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_MeetupSpec_To_v1alpha1_MeetupSpec(a.(*meetops.MeetupSpec), b.(*MeetupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MeetupSponsor)(nil), (*meetops.MeetupSponsor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MeetupSponsor_To_meetops_MeetupSponsor(a.(*MeetupSponsor), b.(*meetops.MeetupSponsor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.MeetupSponsor)(nil), (*MeetupSponsor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_MeetupSponsor_To_v1alpha1_MeetupSponsor(a.(*meetops.MeetupSponsor), b.(*MeetupSponsor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MeetupStatus)(nil), (*meetops.MeetupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MeetupStatus_To_meetops_MeetupStatus(a.(*MeetupStatus), b.(*meetops.MeetupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.MeetupStatus)(nil), (*MeetupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_MeetupStatus_To_v1alpha1_MeetupStatus(a.(*meetops.MeetupStatus), b.(*MeetupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Presentation)(nil), (*meetops.Presentation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Presentation_To_meetops_Presentation(a.(*Presentation), b.(*meetops.Presentation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.Presentation)(nil), (*Presentation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_Presentation_To_v1alpha1_Presentation(a.(*meetops.Presentation), b.(*Presentation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Speaker)(nil), (*meetops.Speaker)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Speaker_To_meetops_Speaker(a.(*Speaker), b.(*meetops.Speaker), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.Speaker)(nil), (*Speaker)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_Speaker_To_v1alpha1_Speaker(a.(*meetops.Speaker), b.(*Speaker), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SpeakerRef)(nil), (*meetops.SpeakerRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SpeakerRef_To_meetops_SpeakerRef(a.(*SpeakerRef), b.(*meetops.SpeakerRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*meetops.SpeakerRef)(nil), (*SpeakerRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_meetops_SpeakerRef_To_v1alpha1_SpeakerRef(a.(*meetops.SpeakerRef), b.(*SpeakerRef), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Company_To_meetops_Company(in *Company, out *meetops.Company, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.ID = meetops.CompanyID(in.ID)
	out.Name = in.Name
	out.WebsiteURL = in.WebsiteURL
	out.LogoURL = in.LogoURL
	out.WhiteLogo = in.WhiteLogo
	return nil
}

// Convert_v1alpha1_Company_To_meetops_Company is an autogenerated conversion function.
func Convert_v1alpha1_Company_To_meetops_Company(in *Company, out *meetops.Company, s conversion.Scope) error {
	return autoConvert_v1alpha1_Company_To_meetops_Company(in, out, s)
}

func autoConvert_meetops_Company_To_v1alpha1_Company(in *meetops.Company, out *Company, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.ID = CompanyID(in.ID)
	out.Name = in.Name
	out.WebsiteURL = in.WebsiteURL
	out.LogoURL = in.LogoURL
	out.WhiteLogo = in.WhiteLogo
	return nil
}

// Convert_meetops_Company_To_v1alpha1_Company is an autogenerated conversion function.
func Convert_meetops_Company_To_v1alpha1_Company(in *meetops.Company, out *Company, s conversion.Scope) error {
	return autoConvert_meetops_Company_To_v1alpha1_Company(in, out, s)
}

func autoConvert_v1alpha1_CompanyRef_To_meetops_CompanyRef(in *CompanyRef, out *meetops.CompanyRef, s conversion.Scope) error {
	out.Ref = (*meetops.Company)(unsafe.Pointer(in.Ref))
	out.ID = meetops.CompanyID(in.ID)
	return nil
}

// Convert_v1alpha1_CompanyRef_To_meetops_CompanyRef is an autogenerated conversion function.
func Convert_v1alpha1_CompanyRef_To_meetops_CompanyRef(in *CompanyRef, out *meetops.CompanyRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_CompanyRef_To_meetops_CompanyRef(in, out, s)
}

func autoConvert_meetops_CompanyRef_To_v1alpha1_CompanyRef(in *meetops.CompanyRef, out *CompanyRef, s conversion.Scope) error {
	out.Ref = (*Company)(unsafe.Pointer(in.Ref))
	out.ID = CompanyID(in.ID)
	return nil
}

// Convert_meetops_CompanyRef_To_v1alpha1_CompanyRef is an autogenerated conversion function.
func Convert_meetops_CompanyRef_To_v1alpha1_CompanyRef(in *meetops.CompanyRef, out *CompanyRef, s conversion.Scope) error {
	return autoConvert_meetops_CompanyRef_To_v1alpha1_CompanyRef(in, out, s)
}

func autoConvert_v1alpha1_Meetup_To_meetops_Meetup(in *Meetup, out *meetops.Meetup, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MeetupSpec_To_meetops_MeetupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MeetupStatus_To_meetops_MeetupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Meetup_To_meetops_Meetup is an autogenerated conversion function.
func Convert_v1alpha1_Meetup_To_meetops_Meetup(in *Meetup, out *meetops.Meetup, s conversion.Scope) error {
	return autoConvert_v1alpha1_Meetup_To_meetops_Meetup(in, out, s)
}

func autoConvert_meetops_Meetup_To_v1alpha1_Meetup(in *meetops.Meetup, out *Meetup, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_meetops_MeetupSpec_To_v1alpha1_MeetupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_meetops_MeetupStatus_To_v1alpha1_MeetupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_meetops_Meetup_To_v1alpha1_Meetup is an autogenerated conversion function.
func Convert_meetops_Meetup_To_v1alpha1_Meetup(in *meetops.Meetup, out *Meetup, s conversion.Scope) error {
	return autoConvert_meetops_Meetup_To_v1alpha1_Meetup(in, out, s)
}

func autoConvert_v1alpha1_MeetupGroup_To_meetops_MeetupGroup(in *MeetupGroup, out *meetops.MeetupGroup, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MeetupGroupSpec_To_meetops_MeetupGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MeetupGroupStatus_To_meetops_MeetupGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MeetupGroup_To_meetops_MeetupGroup is an autogenerated conversion function.
func Convert_v1alpha1_MeetupGroup_To_meetops_MeetupGroup(in *MeetupGroup, out *meetops.MeetupGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_MeetupGroup_To_meetops_MeetupGroup(in, out, s)
}

func autoConvert_meetops_MeetupGroup_To_v1alpha1_MeetupGroup(in *meetops.MeetupGroup, out *MeetupGroup, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_meetops_MeetupGroupSpec_To_v1alpha1_MeetupGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_meetops_MeetupGroupStatus_To_v1alpha1_MeetupGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_meetops_MeetupGroup_To_v1alpha1_MeetupGroup is an autogenerated conversion function.
func Convert_meetops_MeetupGroup_To_v1alpha1_MeetupGroup(in *meetops.MeetupGroup, out *MeetupGroup, s conversion.Scope) error {
	return autoConvert_meetops_MeetupGroup_To_v1alpha1_MeetupGroup(in, out, s)
}

func autoConvert_v1alpha1_MeetupGroupSpec_To_meetops_MeetupGroupSpec(in *MeetupGroupSpec, out *meetops.MeetupGroupSpec, s conversion.Scope) error {
	out.MeetupID = in.MeetupID
	out.Organizers = *(*[]meetops.SpeakerRef)(unsafe.Pointer(&in.Organizers))
	out.IgnoreMeetupDates = *(*[]string)(unsafe.Pointer(&in.IgnoreMeetupDates))
	out.CFP = in.CFP
	out.Latitude = in.Latitude
	out.Longitude = in.Longitude
	out.EcosystemMembers = *(*[]meetops.CompanyRef)(unsafe.Pointer(&in.EcosystemMembers))
	out.Meetups = *(*map[string]meetops.Meetup)(unsafe.Pointer(&in.Meetups))
	return nil
}

// Convert_v1alpha1_MeetupGroupSpec_To_meetops_MeetupGroupSpec is an autogenerated conversion function.
func Convert_v1alpha1_MeetupGroupSpec_To_meetops_MeetupGroupSpec(in *MeetupGroupSpec, out *meetops.MeetupGroupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MeetupGroupSpec_To_meetops_MeetupGroupSpec(in, out, s)
}

func autoConvert_meetops_MeetupGroupSpec_To_v1alpha1_MeetupGroupSpec(in *meetops.MeetupGroupSpec, out *MeetupGroupSpec, s conversion.Scope) error {
	out.MeetupID = in.MeetupID
	out.Organizers = *(*[]SpeakerRef)(unsafe.Pointer(&in.Organizers))
	out.IgnoreMeetupDates = *(*[]string)(unsafe.Pointer(&in.IgnoreMeetupDates))
	out.CFP = in.CFP
	out.Latitude = in.Latitude
	out.Longitude = in.Longitude
	out.EcosystemMembers = *(*[]CompanyRef)(unsafe.Pointer(&in.EcosystemMembers))
	out.Meetups = *(*map[string]Meetup)(unsafe.Pointer(&in.Meetups))
	return nil
}

// Convert_meetops_MeetupGroupSpec_To_v1alpha1_MeetupGroupSpec is an autogenerated conversion function.
func Convert_meetops_MeetupGroupSpec_To_v1alpha1_MeetupGroupSpec(in *meetops.MeetupGroupSpec, out *MeetupGroupSpec, s conversion.Scope) error {
	return autoConvert_meetops_MeetupGroupSpec_To_v1alpha1_MeetupGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_MeetupGroupStatus_To_meetops_MeetupGroupStatus(in *MeetupGroupStatus, out *meetops.MeetupGroupStatus, s conversion.Scope) error {
	out.Photo = in.Photo
	out.Name = in.Name
	out.City = in.City
	out.Country = in.Country
	out.Description = in.Description
	out.SponsorTiers = *(*map[meetops.CompanyID]meetops.SponsorTier)(unsafe.Pointer(&in.SponsorTiers))
	return nil
}

// Convert_v1alpha1_MeetupGroupStatus_To_meetops_MeetupGroupStatus is an autogenerated conversion function.
func Convert_v1alpha1_MeetupGroupStatus_To_meetops_MeetupGroupStatus(in *MeetupGroupStatus, out *meetops.MeetupGroupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MeetupGroupStatus_To_meetops_MeetupGroupStatus(in, out, s)
}

func autoConvert_meetops_MeetupGroupStatus_To_v1alpha1_MeetupGroupStatus(in *meetops.MeetupGroupStatus, out *MeetupGroupStatus, s conversion.Scope) error {
	out.Photo = in.Photo
	out.Name = in.Name
	out.City = in.City
	out.Country = in.Country
	out.Description = in.Description
	out.SponsorTiers = *(*map[CompanyID]SponsorTier)(unsafe.Pointer(&in.SponsorTiers))
	return nil
}

// Convert_meetops_MeetupGroupStatus_To_v1alpha1_MeetupGroupStatus is an autogenerated conversion function.
func Convert_meetops_MeetupGroupStatus_To_v1alpha1_MeetupGroupStatus(in *meetops.MeetupGroupStatus, out *MeetupGroupStatus, s conversion.Scope) error {
	return autoConvert_meetops_MeetupGroupStatus_To_v1alpha1_MeetupGroupStatus(in, out, s)
}

func autoConvert_v1alpha1_MeetupSpec_To_meetops_MeetupSpec(in *MeetupSpec, out *meetops.MeetupSpec, s conversion.Scope) error {
	out.Recording = in.Recording
	out.Sponsors = *(*[]meetops.MeetupSponsor)(unsafe.Pointer(&in.Sponsors))
	out.Presentations = *(*[]meetops.Presentation)(unsafe.Pointer(&in.Presentations))
	return nil
}

// Convert_v1alpha1_MeetupSpec_To_meetops_MeetupSpec is an autogenerated conversion function.
func Convert_v1alpha1_MeetupSpec_To_meetops_MeetupSpec(in *MeetupSpec, out *meetops.MeetupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MeetupSpec_To_meetops_MeetupSpec(in, out, s)
}

func autoConvert_meetops_MeetupSpec_To_v1alpha1_MeetupSpec(in *meetops.MeetupSpec, out *MeetupSpec, s conversion.Scope) error {
	out.Recording = in.Recording
	out.Sponsors = *(*[]MeetupSponsor)(unsafe.Pointer(&in.Sponsors))
	out.Presentations = *(*[]Presentation)(unsafe.Pointer(&in.Presentations))
	return nil
}

// Convert_meetops_MeetupSpec_To_v1alpha1_MeetupSpec is an autogenerated conversion function.
func Convert_meetops_MeetupSpec_To_v1alpha1_MeetupSpec(in *meetops.MeetupSpec, out *MeetupSpec, s conversion.Scope) error {
	return autoConvert_meetops_MeetupSpec_To_v1alpha1_MeetupSpec(in, out, s)
}

func autoConvert_v1alpha1_MeetupSponsor_To_meetops_MeetupSponsor(in *MeetupSponsor, out *meetops.MeetupSponsor, s conversion.Scope) error {
	out.Role = meetops.SponsorRole(in.Role)
	if err := Convert_v1alpha1_CompanyRef_To_meetops_CompanyRef(&in.Company, &out.Company, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MeetupSponsor_To_meetops_MeetupSponsor is an autogenerated conversion function.
func Convert_v1alpha1_MeetupSponsor_To_meetops_MeetupSponsor(in *MeetupSponsor, out *meetops.MeetupSponsor, s conversion.Scope) error {
	return autoConvert_v1alpha1_MeetupSponsor_To_meetops_MeetupSponsor(in, out, s)
}

func autoConvert_meetops_MeetupSponsor_To_v1alpha1_MeetupSponsor(in *meetops.MeetupSponsor, out *MeetupSponsor, s conversion.Scope) error {
	out.Role = SponsorRole(in.Role)
	if err := Convert_meetops_CompanyRef_To_v1alpha1_CompanyRef(&in.Company, &out.Company, s); err != nil {
		return err
	}
	return nil
}

// Convert_meetops_MeetupSponsor_To_v1alpha1_MeetupSponsor is an autogenerated conversion function.
func Convert_meetops_MeetupSponsor_To_v1alpha1_MeetupSponsor(in *meetops.MeetupSponsor, out *MeetupSponsor, s conversion.Scope) error {
	return autoConvert_meetops_MeetupSponsor_To_v1alpha1_MeetupSponsor(in, out, s)
}

func autoConvert_v1alpha1_MeetupStatus_To_meetops_MeetupStatus(in *MeetupStatus, out *meetops.MeetupStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Photo = in.Photo
	out.Name = in.Name
	out.Date = in.Date
	out.Duration = in.Duration
	out.Attendees = in.Attendees
	out.Address = in.Address
	return nil
}

// Convert_v1alpha1_MeetupStatus_To_meetops_MeetupStatus is an autogenerated conversion function.
func Convert_v1alpha1_MeetupStatus_To_meetops_MeetupStatus(in *MeetupStatus, out *meetops.MeetupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MeetupStatus_To_meetops_MeetupStatus(in, out, s)
}

func autoConvert_meetops_MeetupStatus_To_v1alpha1_MeetupStatus(in *meetops.MeetupStatus, out *MeetupStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Photo = in.Photo
	out.Name = in.Name
	out.Date = in.Date
	out.Duration = in.Duration
	out.Attendees = in.Attendees
	out.Address = in.Address
	return nil
}

// Convert_meetops_MeetupStatus_To_v1alpha1_MeetupStatus is an autogenerated conversion function.
func Convert_meetops_MeetupStatus_To_v1alpha1_MeetupStatus(in *meetops.MeetupStatus, out *MeetupStatus, s conversion.Scope) error {
	return autoConvert_meetops_MeetupStatus_To_v1alpha1_MeetupStatus(in, out, s)
}

func autoConvert_v1alpha1_Presentation_To_meetops_Presentation(in *Presentation, out *meetops.Presentation, s conversion.Scope) error {
	out.Duration = in.Duration
	out.Delay = (*v1.Duration)(unsafe.Pointer(in.Delay))
	out.Title = in.Title
	out.Slides = in.Slides
	out.Recording = in.Recording
	out.Speakers = *(*[]meetops.SpeakerRef)(unsafe.Pointer(&in.Speakers))
	return nil
}

// Convert_v1alpha1_Presentation_To_meetops_Presentation is an autogenerated conversion function.
func Convert_v1alpha1_Presentation_To_meetops_Presentation(in *Presentation, out *meetops.Presentation, s conversion.Scope) error {
	return autoConvert_v1alpha1_Presentation_To_meetops_Presentation(in, out, s)
}

func autoConvert_meetops_Presentation_To_v1alpha1_Presentation(in *meetops.Presentation, out *Presentation, s conversion.Scope) error {
	out.Duration = in.Duration
	out.Delay = (*v1.Duration)(unsafe.Pointer(in.Delay))
	out.Title = in.Title
	out.Slides = in.Slides
	out.Recording = in.Recording
	out.Speakers = *(*[]SpeakerRef)(unsafe.Pointer(&in.Speakers))
	return nil
}

// Convert_meetops_Presentation_To_v1alpha1_Presentation is an autogenerated conversion function.
func Convert_meetops_Presentation_To_v1alpha1_Presentation(in *meetops.Presentation, out *Presentation, s conversion.Scope) error {
	return autoConvert_meetops_Presentation_To_v1alpha1_Presentation(in, out, s)
}

func autoConvert_v1alpha1_Speaker_To_meetops_Speaker(in *Speaker, out *meetops.Speaker, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.ID = meetops.SpeakerID(in.ID)
	out.Name = in.Name
	out.Title = in.Title
	out.Email = in.Email
	if err := Convert_v1alpha1_CompanyRef_To_meetops_CompanyRef(&in.Company, &out.Company, s); err != nil {
		return err
	}
	out.Github = in.Github
	out.Twitter = in.Twitter
	out.SpeakersBureau = in.SpeakersBureau
	return nil
}

// Convert_v1alpha1_Speaker_To_meetops_Speaker is an autogenerated conversion function.
func Convert_v1alpha1_Speaker_To_meetops_Speaker(in *Speaker, out *meetops.Speaker, s conversion.Scope) error {
	return autoConvert_v1alpha1_Speaker_To_meetops_Speaker(in, out, s)
}

func autoConvert_meetops_Speaker_To_v1alpha1_Speaker(in *meetops.Speaker, out *Speaker, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	out.ID = SpeakerID(in.ID)
	out.Name = in.Name
	out.Title = in.Title
	out.Email = in.Email
	if err := Convert_meetops_CompanyRef_To_v1alpha1_CompanyRef(&in.Company, &out.Company, s); err != nil {
		return err
	}
	out.Github = in.Github
	out.Twitter = in.Twitter
	out.SpeakersBureau = in.SpeakersBureau
	return nil
}

// Convert_meetops_Speaker_To_v1alpha1_Speaker is an autogenerated conversion function.
func Convert_meetops_Speaker_To_v1alpha1_Speaker(in *meetops.Speaker, out *Speaker, s conversion.Scope) error {
	return autoConvert_meetops_Speaker_To_v1alpha1_Speaker(in, out, s)
}

func autoConvert_v1alpha1_SpeakerRef_To_meetops_SpeakerRef(in *SpeakerRef, out *meetops.SpeakerRef, s conversion.Scope) error {
	out.Ref = (*meetops.Speaker)(unsafe.Pointer(in.Ref))
	out.ID = meetops.SpeakerID(in.ID)
	return nil
}

// Convert_v1alpha1_SpeakerRef_To_meetops_SpeakerRef is an autogenerated conversion function.
func Convert_v1alpha1_SpeakerRef_To_meetops_SpeakerRef(in *SpeakerRef, out *meetops.SpeakerRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_SpeakerRef_To_meetops_SpeakerRef(in, out, s)
}

func autoConvert_meetops_SpeakerRef_To_v1alpha1_SpeakerRef(in *meetops.SpeakerRef, out *SpeakerRef, s conversion.Scope) error {
	out.Ref = (*Speaker)(unsafe.Pointer(in.Ref))
	out.ID = SpeakerID(in.ID)
	return nil
}

// Convert_meetops_SpeakerRef_To_v1alpha1_SpeakerRef is an autogenerated conversion function.
func Convert_meetops_SpeakerRef_To_v1alpha1_SpeakerRef(in *meetops.SpeakerRef, out *SpeakerRef, s conversion.Scope) error {
	return autoConvert_meetops_SpeakerRef_To_v1alpha1_SpeakerRef(in, out, s)
}
